### ISSUE TITLE
Bug in wiring diagram for I2S sample

### ISSUE THREAD

**Issue by msrcstuart** [CodethinkLabs/mt3620-m4-samples#11]
There is a bug in the wiring diagram for the I2S sample. The I2C pull-up resistors should be connected to 3.3V (as described in the README), however, the wiring diagram has the pull-ups connected to the 5V pin of the MT3620 dev board.

**Comment by aiden-ct** [comment]
Thank you! I'd missed this one in the cleanup the other week.
