### ISSUE TITLE
SDCARD Write/Read

### ISSUE THREAD

**Issue by taylor-an** [CodethinkLabs/mt3620-m4-samples#23]
@aiden-ct  Thank you for commit to WriteBlock().

I tested at that time but I gave up to develop SDCARD Fat fs.
I trying to develop it again.

I tried to write and read blocks, from 0 to the end.
I used to SDCARD of Sandisk microSD HC1 class 4, 4GB capacity.
But I got too many errors to write and read till the end. The SPI clock was 250KHz, 2MHz, 20MHz.

When I got errors, I try to do SD_Close(), SPIMaster_Close() and SPIMaster_Open(), SD_Open() to retry to failed block. Well, it works.

But, I wonder is it right or not.
Is it possible to clearly(I mean without error)write and read all blocks?

And, if you can tell me the details of the SDCARD you tested.

**Comment by aiden-ct** [comment]
Hi @taylor-an - we tested with a few different cards, the cards I have with me are Transcend 2GB and Sandisk 16GB, but more are detailed in the sample README.

I've added a patch to the sample today that I believe will fix the issue you're having. I've switched the timer to GPT3 and added a stop to the timeout timer.

**Comment by aiden-ct** [comment]
@taylor-an - let me know how you get on and if my patch fixes things for you.

**Comment by taylor-an** [comment]
@aiden-ct Thank you.
It works very well. I can't see any errors.

**Comment by aiden-ct** [comment]
Great. Thanks for the bug report.
