### ISSUE TITLE
Need to run ./utils/update_submodules.sh after cloning to get libs in folders.

### ISSUE THREAD

**Issue by ongchris** [CodethinkLabs/mt3620-m4-samples#25]
After pulling the code, I needed to run ./utils/update_submodules.sh after cloning to get libs in folders. Otherwise, the build will fail. I did not see this step in the README. Is this expected?

**Comment by aiden-ct** [comment]
HI @ongchris - you need to run `git submodule update --init` after cloning the samples directory (see the [cloning](https://github.com/CodethinkLabs/mt3620-m4-samples/blob/master/README.md#cloning) instructions), this clones all of the libs directories to the sha specified in the `.gitmodules` file. The `update_submodules.sh` script is mainly for development and pointing all the libs at a new HEAD for testing / updating.
