### ISSUE TITLE
Submodule using ssh URL not https, prevents cloning for users without registered ssh keys

### ISSUE THREAD

**Issue by cawhitworth** [CodethinkLabs/mt3620-m4-samples#26]
See .gitmodules - the last submodule entry:

```
[submodule "EINT_RTApp_MT3620_BareMetal/lib"]
        path = EINT_RTApp_MT3620_BareMetal/lib
        url = git@github.com:CodethinkLabs/mt3620-m4-drivers.git
```

Uses an ssh URL, which will require auth. This prevents cloning by users who do not have an ssh key registered with Github.

**Comment by aiden-ct** [comment]
Thanks for spotting that, and for fixing it.
