### ISSUE TITLE
Please provide the detailed syntax to run SPI\I2C RTapps with upgraded targeted API Set.

### ISSUE THREAD

**Issue by Shieroo** [CodethinkLabs/mt3620-m4-samples#4]
When I ran the SPI \ I2C RTapp sample using the 20.04 SDK (Azure Sphere, Sysroot 5 \ 5+Beta - Latest-Beta) it was not compatible. I had to modify some codes in CmakeLists.txt and CmakeSettings.json to make it succeeded. However, there is no detailed guide on this and it takes some time to figure it out. 

Please add them in Readme.md or upgrade your sample codes.

**Comment by aiden-ct** [comment]
I will update to the latest SDK and include instructions locally. I'm not in the office for the next 2 weeks, but will add as soon as possible.
